fruits=[]
f1=input("enter the fruits numbe:-")
fruits.append(f1)
f2=input("enter the fruits numbe:-")
fruits.append(f2)
f3=input("enter the fruits numbe:-")
fruits.append(f3)
f4=input("enter the fruits numbe:-")
fruits.append(f4)
f5=input("enter the fruits numbe:-")
fruits.append(f5)
f6=input("enter the fruits numbe:-")
fruits.append(f6)
f7=input("enter the fruits numbe:-")
fruits.append(f7)
f8=input("enter the fruits numbe:-")
fruits.append(f8)
print(fruits)