marks=[]
f1=input("enter the marks numbe:-")
marks.append(f1)
f2=input("enter the marks numbe:-")
marks.append(f2)
f3=input("enter the marks numbe:-")
marks.append(f3)
f4=input("enter the marks numbe:-")
marks.append(f4)
f5=input("enter the marks numbe:-")
marks.append(f5)
f6=input("enter the marks numbe:-")
marks.append(f6)
f7=input("enter the marks numbe:-")
marks.append(f7)
f8=input("enter the marks numbe:-")
marks.append(f8)
marks.sort()
print(marks)