s=set()
n=int(input("enter the number1:-"))
s.add(n)
n=int(input("enter the number:-"))
s.add(n)
n=int(input("enter the number:-"))
s.add(n)
n=int(input("enter the number:-"))
s.add(n)
n=int(input("enter the number:-"))
s.add(n)
print(s)
